<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>MyBookShelf.GraphQLSchema</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="HotChocolate.Types" Version="15.1.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\MyBookShelf.Domain\MyBookShelf.Domain.csproj" />
    </ItemGroup>

</Project>
